/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


/*** Standard libraries ***/
#include <stdlib.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

/*** MCU Specific Header File ***/
#include "STM32F413ZHT6_specific.h"



int main(void)
{


	GPIOA_CLK_EN();
	I2C_Clock_Enable(I2C1);




	while(1)
	{


	}	// end of while(1)


} // end of main




