/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


/*** Standard libraries ***/
#include <stdlib.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

/*** MCU Specific Header File ***/
#include "STM32F413ZHT6_specific.h"



int main(void)
{

	// Create a class of type LCD_PINOUT_t that holds all the desired pinout information
	// This information is used in future functions
	LCD_PINOUT_t LCD;

	// Designate the RS pins
	LCD.LCD_RS.port = (uint32_t)GPIOA;
	LCD.LCD_RS.pin = 7;

	// Designate the RW pins
	LCD.LCD_RW.port = (uint32_t)GPIOB;
	LCD.LCD_RW.pin = 11;

	// Designate the EN pins
	LCD.LCD_EN.port = (uint32_t)GPIOC;
	LCD.LCD_EN.pin = 11;

	// Designate the D4 pins
	LCD.LCD_D4.port = (uint32_t)GPIOD;
	LCD.LCD_D4.pin = 4;

	// Designate the D5 pins
	LCD.LCD_D5.port = (uint32_t)GPIOD;
	LCD.LCD_D5.pin = 5;

	// Designate the D6 pins
	LCD.LCD_D6.port = (uint32_t)GPIOD;
	LCD.LCD_D6.pin = 6;

	// Designate the D7 pins
	LCD.LCD_D7.port = (uint32_t)GPIOD;
	LCD.LCD_D7.pin = 7;

	// initialize the designated pins to GPIO outputs
	LCD_Pin_Init(&LCD);













	while(1)
	{



	}	// end of while(1)


} // end of main




